Models/AutoParkingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoParking.Models
{
    public class AutoParkingModel
    {
        public int Id { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int pojemnoscsilnik { get; set; }
        public int Rokprod { get; set; }
        public int cena { get; set; }
        public bool czysprzedany { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AutoParking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AutoParkingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoParking.Models;
namespace AutoParking.Controllers
{
    public class AutoParkingController : Controller
    {

        AutoParkingManager AutoParkingManager = new AutoParkingManager();
        public IActionResult Index()
        {
           

           var list = AutoParkingManager.GetAutos();
            return View(list);
        }
        [HttpGet]
        public IActionResult Add()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Add(AutoParkingModel automodel)
        {
            
            AutoParkingManager.AddAuto(automodel);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Remove(int id)
        {
            var auto = AutoParkingManager.GetAuto(id);
            return View(auto);
        }
        [HttpPost]
        public IActionResult RemoveConfirm(int id) 
        {
            AutoParkingManager.RemoveAuto(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
           var auto= AutoParkingManager.GetAuto(id);
            return View(auto);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var auto = AutoParkingManager.GetAuto(id);
            return View(auto);
        }
        [HttpPost]
        public IActionResult Edit(AutoParkingModel automodel)
        {
            AutoParkingManager.UpdateAuto(automodel);
            return RedirectToAction("Index"); 
        }
        public IActionResult SprzedajAuto(int id)
        {
            var auto = AutoParkingManager.GetAuto(id);
            AutoParkingManager.sprzedajAuto(auto);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using AutoParking.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AutoParking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AutoParking/Add.cshtml
@model AutoParking.Models.AutoParkingModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>AutoParkingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pojemnoscsilnik" class="control-label"></label>
                <input asp-for="pojemnoscsilnik" class="form-control" />
                <span asp-validation-for="pojemnoscsilnik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rokprod" class="control-label"></label>
                <input asp-for="Rokprod" class="form-control" />
                <span asp-validation-for="Rokprod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cena" class="control-label"></label>
                <input asp-for="cena" class="form-control" />
                <span asp-validation-for="cena" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="czysprzedany" /> @Html.DisplayNameFor(model => model.czysprzedany)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AutoParking/Details.cshtml
@model AutoParking.Models.AutoParkingModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AutoParkingModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pojemnoscsilnik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pojemnoscsilnik)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rokprod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rokprod)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.czysprzedany)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.czysprzedany)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
    <a asp-action="sprzedajAuto" asp-route-id="@Model.Id">Sprzedaj</a>
    <a asp-action="Index">Back to List</a>
</div>

Views/AutoParking/Edit.cshtml
@model AutoParking.Models.AutoParkingModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>AutoParkingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pojemnoscsilnik" class="control-label"></label>
                <input asp-for="pojemnoscsilnik" class="form-control" />
                <span asp-validation-for="pojemnoscsilnik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rokprod" class="control-label"></label>
                <input asp-for="Rokprod" class="form-control" />
                <span asp-validation-for="Rokprod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cena" class="control-label"></label>
                <input asp-for="cena" class="form-control" />
                <span asp-validation-for="cena" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="czysprzedany" /> @Html.DisplayNameFor(model => model.czysprzedany)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AutoParking/Index.cshtml
@model IEnumerable<AutoParking.Models.AutoParkingModel>

@{
    ViewData["Title"] = "Lista Aut";
}

<h1>Lista Aut</h1>

<p>
    <button type="button" asp-action="Add" class="btn btn-dark">Dodaj nowy</button>
</p>
<table class="table table-striped" >
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pojemnoscsilnik)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rokprod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.czysprzedany)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pojemnoscsilnik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rokprod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.czysprzedany)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Właściwości</a> |
                <a asp-action="Remove" asp-route-id="@item.Id">Usuń</a>
                
            </td>
        </tr>
}
    </tbody>
</table>

Views/AutoParking/Remove.cshtml
@model AutoParking.Models.AutoParkingModel

@{
    ViewData["Title"] = "Remove";
}

<h1>Remove</h1>

<h3>Jesteś pewny ze chcesz usunac??</h3>
<div>
    <h4>AutoParkingModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pojemnoscsilnik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pojemnoscsilnik)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rokprod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rokprod)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.czysprzedany)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.czysprzedany)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remove" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoParking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="AutoParking" asp-action="Index">AutoParking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AutoParking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>